name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  ACR_NAME: myContainerRegistry
  ACR_LOGIN_SERVER: myContainerRegistry.azurecr.io
  IMAGE_NAME: portfoliowebsite
  RESOURCE_GROUP: myResourceGroup
  CONTAINER_INSTANCE: mycontainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Azure CLI - Log in
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instance
      run: |
        az container create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.CONTAINER_INSTANCE }} \
          --image ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest \
          --cpu 1 \
          --memory 1 \
          --registry-login-server ${{ env.ACR_LOGIN_SERVER }} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --dns-name-label myflaskapp \
          --ports 80 \
        || az container update \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.CONTAINER_INSTANCE }} \
          --image ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
